version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - "3001:3001"  # Host:3001 → Container:3001
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/notifications
      PORT: 3001
    networks:
      - auth_service_default

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notifications"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - auth_service_default

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - auth_service_default

volumes:
  db_data:

networks:
  auth_service_default:
    external: true